### ISSUE TITLE
Combine frontend `reg-event-fx` responses from server

### ISSUE THREAD

**Issue by tctrautman** [probcomp/curve-fitting#13]
https://github.com/probcomp/curve-fitting/blob/0ded0bb58814db2ab1beba9517d8edec959466da/src/equations/canvas.cljs#L173-L195

Per Zane, in reference to `::rm-posts-failure`:

```We could combine these with the other two HTTP success and failure event handlers since they basically do the same thing. What we'd want to do in that case is change :on-success such that the events dispatched (currently [::point-post-success] and [::point-post-failure]) contain information (probably the URI and params?) about the HTTP request that failed.```

**Comment by zane** [comment]
No longer relevant as of #16.
