### ISSUE TITLE
Don't refer let in curve-fitting.model

### ISSUE THREAD

**Issue by zane** [probcomp/curve-fitting#23]
It is unused.

**Comment by tctrautman** [comment]
I want to make sure I understand the goal here.  Am I right in thinking you want to remove this line? https://github.com/probcomp/curve-fitting/blob/master/src/curve_fitting/model.clj#L2

My only exposure to `refer-clojure` is from its ClojureDocs page, so I'm probably missing something, but it looks to me like this line _is_ being used here: https://github.com/probcomp/curve-fitting/blob/master/src/curve_fitting/model.clj#L26

Any guidance here would be appreciated!

**Comment by alex-lew** [comment]
@tctrautman The `refer-clojure` statement is bringing in two names: `let` and `reduce`. `reduce` is used (as you point out), but `let` isn't :-) (The syntax coloring on Github makes it a bit confusing.)

**Comment by tctrautman** [comment]
Ah, got it.  Thank you!
