### ISSUE TITLE
Make figwheel server a redirect on its HTTP port

### ISSUE THREAD

**Issue by joshuathayer** [probcomp/curve-fitting#5]
Figwheel by default opens port `3000` and serves `resources/public/index.html`. In our case, the html which hosts the client app should be generated by the ring server, so it can include a dynamically-generated CSRF token (by default, our ring server listens on `3333`). So, any user which visits the "old" static page as served by figwheel will be disappointed when nothing works.

Either somehow configure figwheel to return a redirect to `3333`, or update the content of `index.html` to do the same.

**Comment by zane** [comment]
No longer relevant as of #16.
